# This file stores your secret credentials.
# Replace placeholders with your actual credentials.

[database]
db_url = "Your url"

[twitter]
bearer_token = "Your token"

[google_ai]
api_key = "Your key"
