# This file stores your secret credentials.
# Replace placeholders with your actual credentials.

[database]
db_url = "postgresql://postgres:root@localhost:5432/sentiments"

[twitter]
bearer_token = "AAAAAAAAAAAAAAAAAAAAAKq23QEAAAAAvHX9I3CrN6qtcumbKYyKVKGPME0%3DsuUmueQPsCrXIQYG9QGS14Jd8UYuqWxh8QyEpwjWgNIk1B7FNv"

[google_ai]
api_key = "AIzaSyDWMwBI4ywxX5cz886lR2jb3QFnHPZPlZU"